language: android
jdk:
- oraclejdk8
env:
  global:
  - ADB_INSTALL_TIMEOUT=8
android:
  components:
  - tools
  - platform-tools
  - extra-google-m2repository
  - extra-android-m2repository
  - build-tools-25.0.3
  - android-25
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew --info assembleDebug"

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HTIRs9ihkKaETyol9BRR/DYliGtZ3C2NzDJSRnI1GfsPxKq51fwjg/ejKRkS1j3Xp/HSRqvhyFynHuSqkZUORQ4fIGcorCmRiMos/g5HO4lMSmAH2Xw5AXr7s8QuHawG6vppkUbYwZy1EaeVc2OdWBsjBziZMyiQndZxOQ+inSpuI6UFRcGOSOo88bKn86lJ4G8DzbEapzpeqxB++HNHpd4LsguFJpOQvXg9aJGZxYiywiZgxqkhAvlhu49YW8UT66Keq7EpVZ2NE9EBNsA2AdcQyBEwy+yTEwqTNJGzM0yADcucPX90MPLMBCu1b0BMT+eT/+NG8/NmXC+nLT9Z/uRBWq+oekRP5G6X9P5jSe+qfXLXUJvDBD0ygNVfpp+6/9Ljt9EtXXTRKp9z0f9cGl45ILrYCRB0zgpQL3GirLir2uoO3ZA60r0kCQIVF8PTT+xbswAd/2YtIApoXlKDqn9kN31FRuh97/4ey/RBR6ePqNzltThXhuZsGr5QXrvCvt8rBdb51YOcrp8e0FMZS8EMqUetIEURwkB8BYR4OL2TIlEj4ZFk+dnanVOtcwOrLMTqkTHhra8i/W0it5hQuc/RsAeVGziDoaxWCIsp/t4o4b5glwiTizUP0LA1KEnJBqDX6iMwQPZqilJRiFSf6YEcUkhmKvBn5Hz/muT3j84=
  file: app/build/outputs/apk/app-debug.apk
  on:
    tags: true
